name: select_modal_flutter
description: Flutter package to create a select with its options in a modal window with search filter.
version: 0.0.2
homepage: https://github.com/javiomoreno/select_modal_flutter

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
